//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalTests.Modelka
{
    using System;
    using System.Collections.Generic;
    
    public partial class mkb_codes
    {
        public int ID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
    }
}
