//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalTests.Modelka
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArmDentalEntities : DbContext
    {
        public ArmDentalEntities()
            : base("name=ArmDentalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<appointment> appointment { get; set; }
        public virtual DbSet<consumables> consumables { get; set; }
        public virtual DbSet<login> login { get; set; }
        public virtual DbSet<med_history> med_history { get; set; }
        public virtual DbSet<mkb_codes> mkb_codes { get; set; }
        public virtual DbSet<patients> patients { get; set; }
    }
}
