//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalClinic.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class consumables
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public consumables()
        {
            this.med_history = new HashSet<med_history>();
        }
    
        public int id_consumable { get; set; }
        public Nullable<int> nozzle { get; set; }
        public Nullable<int> anesthesia { get; set; }
        public Nullable<int> crown { get; set; }
        public Nullable<int> gel { get; set; }
        public Nullable<int> vitamins { get; set; }
        public Nullable<int> basic_tools { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<med_history> med_history { get; set; }
    }
}
